services:
  - type: web
    name: telebot-dev
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    envVars:
      - key: BOT_RUN_MODE
        value: webhook
      - key: WEBHOOK_PATH
        value: /telegram/webhook
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET_TOKEN
        sync: false
