RESEARCH_PLANNER_PROMPT = (
    "Decide whether this generic research packet requires external web research. "
    "If research is needed, return up to 5 concrete web search queries focused on articles, "
    "docs, company websites, product pages, publications, or PDFs. "
    "Do not target social-media pages. Prefer concrete primary sources and current articles. "
    "Queries should bias toward results from the last 3 days."
)

RESEARCH_SYNTHESIS_AGENT_PROMPT = (
    "Review the tweet context, ranked reply context, and grounded evidence. "
    "Identify what the post is really about, which claims matter, and which details meaningfully expand the story. "
    "Use only the provided grounded evidence. Select only sources that were actually used. "
    "Choose purpose using this rubric: "
    "Post is best when the tweet inspires a fresh standalone take, synthesis, framework, or contrarian viewpoint. "
    "Quote is best when the original post is strong and adding a short framing or opinion on top of it is the highest-leverage move. "
    "Comment is best when the best value is replying directly to the author or thread with a pointed, useful, additive response. "
    "Strong original author plus a high-quality top-ranked post pushes toward Quote. "
    "Strong reply opportunities in reply context push toward Comment. "
    "A broad idea with room for independent expansion pushes toward Post. "
    "Evaluate all three purposes explicitly, explain briefly why each is or is not suitable, then choose the best one. "
    "Return purpose_scores on a 0 to 10 scale for post, quote, and comment, and include a concise purpose_rationale for the final choice. "
    "Write agent_comments as a detailed internal brief for a content creator who is a software engineer, SaaS builder, and tech enthusiast. "
    "The brief must not sound like a news report, analyst note, PR memo, or formal media writeup. "
    "It should help the creator sound like a sharp builder reacting to something interesting in the market. "
    "Explain the post's core idea, the strongest grounded takeaways from research, "
    "and concrete content possibilities, hooks, angles, counterpoints, or follow-up directions the creator can write about. "
    "Bias toward informal, high-signal framing such as product implications, engineering implications, distribution lessons, strategic tension, "
    "what feels overhyped, what feels genuinely important, what builders should watch, and what the creator could say in a first-person voice. "
    "Distinguish clearly between: "
    "1) facts the creator can safely state from the evidence, "
    "2) interpretations or spicy-but-defensible takes, and "
    "3) open questions worth bringing to followers. "
    "Do not coach the creator to sound like a neutral reporter. "
    "Do not overuse cautious newsroom language such as repeated 'according to reports' framing in every recommendation. "
    "Use source attribution only where needed to avoid overstating uncertain claims. "
    "Do not imitate any specific real person. Instead, aim for the general feel of a credible, opinionated technical builder on X. "
    "Judge whether the available evidence is sufficient to form a grounded opinion and content recommendation. "
    "If evidence is insufficient, set evidence_sufficient to false and return retry_guidance describing what is missing "
    "so the planner can try again. Return structured output only."
)
